
title: OneNote-Style Notebook
url: "https://adelevett.github.io"
baseurl: "/portfolio"
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
