name: Build and publish GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Grant explicit permissions required for pushing and Pages deployment.
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # ensure we have the full history (some pushes require it) and
          # that credentials are available to push back to the repo
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.9'

      - name: Install Bundler and dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the site with Jekyll
        run: bundle exec jekyll build --trace -d ./_site

      - name: Inspect generated site
        run: |
          echo "--- _site listing ---"
          ls -laR _site || true
          echo "--- head of _site/index.html (if present) ---"
          if [ -f _site/index.html ]; then sed -n '1,120p' _site/index.html || true; else echo "_site/index.html not found"; fi

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          commit_message: "Deploy site from Actions"
          user_name: "github-actions[bot]"
          user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          allow_empty_commit: true
